### ISSUE TITLE
How is Pronto different from Bach?

### ISSUE THREAD

**Issue by ghost** [vadimdemedes/pronto#2]
It appears that both are trying to accomplish similar things. Is one better than the other? [Bach](https://github.com/compose/bach) is being maintained by Compose, which makes it seem like a more reliable choice for the long term.

I'm new to hosted DB world, so sorry if this is a dumb question.

Thanks!

**Comment by vadimdemedes** [comment]
I never tried it, is it easier to use than Pronto? What commands do you need to run to deploy a database and receive connection details to it?

**Comment by ghost** [comment]
@vadimdemedes Bach's CLI API seems to be comprehensive (deploy with one command, with DB name and DB type passed as params), although not as interactive as Pronto's. 

Closing, since I ended up not using Compose, so I'm not motivated to investigate further. Feel free to reopen. 

Thanks!
